version: "3.1"

services:
  frontend:
    container_name: okteto-ui
    image: kabandr/okteto-ui
    restart: unless-stopped
    ports:
      - 8080:80

  backend:
    container_name: okteto-api
    image: kabandr/okteto-api
    restart: unless-stopped
    ports:
      - 5000:5000

  postgres:
    container_name: okteto-db
    image: "postgres:12.2-alpine"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
